/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "error": "#ffb4ab",
        "on-background": "#e5e2e1",
        "error-container": "#93000a",
        "primary-fixed-dim": "#c6c6c7",
        "on-secondary-fixed": "#410000",
        "on-error-container": "#ffdad6",
        "on-error": "#690005",
        "surface-container": "#201f1f",
        "on-tertiary-fixed-variant": "#474746",
        "tertiary-fixed": "#e4e2e1",
        "secondary": "#ffb4a8",
        "outline-variant": "#444748",
        "surface-tint": "#c6c6c7",
        "secondary-fixed": "#ffdad4",
        "on-secondary-container": "#5c0000",
        "on-tertiary-container": "#656464",
        "tertiary-container": "#e4e2e1",
        "primary": "#ffffff",
        "on-primary-container": "#636565",
        "on-tertiary-fixed": "#1b1c1c",
        "on-secondary-fixed-variant": "#930100",
        "surface-container-highest": "#353534",
        "surface-bright": "#3a3939",
        "surface-variant": "#353534",
        "on-surface-variant": "#c4c7c8",
        "on-surface": "#e5e2e1",
        "on-primary-fixed-variant": "#454747",
        "surface-dim": "#131313",
        "tertiary-fixed-dim": "#c8c6c5",
        "inverse-primary": "#5d5f5f",
        "secondary-container": "#ff5540",
        "on-primary-fixed": "#1a1c1c",
        "tertiary": "#ffffff",
        "outline": "#8e9192",
        "surface-container-low": "#1c1b1b",
        "on-primary": "#2f3131",
        "primary-fixed": "#e2e2e2",
        "inverse-surface": "#e5e2e1",
        "on-secondary": "#690100",
        "surface": "#131313",
        "surface-container-lowest": "#0e0e0e",
        "secondary-fixed-dim": "#ffb4a8",
        "inverse-on-surface": "#313030",
        "surface-container-high": "#2a2a2a",
        "primary-container": "#e2e2e2",
        "background": "#131313",
        "on-tertiary": "#303030"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "sidebar-width": "64px",
        "data-row-height": "32px",
        "gutter": "1px",
        "container-margin": "24px",
        "unit": "4px"
      },
      "fontFamily": {
        "data-tabular": ["JetBrains Mono"],
        "label-caps": ["JetBrains Mono"],
        "headline-md": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-sm": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-lg": ["JetBrains Mono"],
        "body-md": ["JetBrains Mono"]
      },
      "fontSize": {
        "data-tabular": ["13px", {"lineHeight": "1.2", "letterSpacing": "0em", "fontWeight": "500"}],
        "label-caps": ["11px", {"lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "700"}],
        "headline-md": ["24px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-sm": ["18px", {"lineHeight": "1.4", "letterSpacing": "0.02em", "fontWeight": "600"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "body-lg": ["16px", {"lineHeight": "1.6", "letterSpacing": "-0.01em", "fontWeight": "400"}],
        "body-md": ["14px", {"lineHeight": "1.6", "letterSpacing": "0em", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
